
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import json
from pathlib import Path
from API.api import ChatRoom

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

    global ID
    global PW

window = Tk()

window.iconbitmap(relative_to_assets("3_icon.ico"))
window.title("UDA Chat")
window.geometry("450x700")
window.configure(bg = "#FFF5EB")

login_id = ''
login_pw = ''

canvas = Canvas(
    window,
    bg = "#FFF5EB",
    height = 700,
    width = 450,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    103.8773193359375,
    466.90625,
    anchor="nw",
    text="ID",
    fill="#000000",
    font=("Arial", 17 * -1)
)

canvas.create_text(
    99.0,
    553.125,
    anchor="nw",
    text="PW",
    fill="#000000",
    font=("Arial", 17 * -1)
)


# If login_Button State == 'Active'
def sign_in():
    if ID == '':
        messagebox.showerror("ID Error", "Please enter your ID.")
    elif PW == '':
        messagbox.showerror("PW Error", "Please enter your PW.")
    else:
        data = {"uname":ID, "upw":PW}
        result = User().UserSignIn(data)

        if result["status"] == 200:
            messagebox.showinfo("Success", "Sign In Successful")
            # gui 전환
        else:
            messagebox.showerror("Error", "Sign In Failed")


# If su_button state == 'Active'
def sign_up():
    if ID == '':
        messagebox.showerror("ID Error", "Please enter your ID.")
    elif PW == '':
        messagebox.showerror("PW Error", "Please enter your PW.")
    else:
        data = {"UserName": ID, "UserAccountPW": PW}
        result = User().UserRegister(data=data)
        if result["status"] == 201:
            messagebox.showinfo("Success", "Sign Up Successful")
        else:
            messagebox.showerror("Error", "Sign Up Failed")


# ID & PW Entry
entry_id = Entry(window, font=('Arial 12'), bd = 0)
entry_pw = Entry(window, font=('Arial 12'), bd = 0, show ='*')
entry_id.place(x = 145, y = 462, width = 207, height = 30)
entry_pw.place(x = 145, y = 547, width = 207, height = 30)

ID = entry_id.get()
PW = entry_pw.get()

# Sign In Button
si_button = Button(
    window,
    command=sign_in,
    bd=0,
    bg='#FFF5EB',
    activebackground='#FFF5EB',
    text='Sign In',
    font=("Arial " + str(16 * 1) + " underline"),
    anchor="nw"
)
si_button.place(x=263, y=625)

# Sign Up Button
su_button = Button(
    window,
    command= sign_up,
    bd=0,
    bg='#FFF5EB',
    activebackground='#FFF5EB',
    text='Sign Up',
    font=("Arial "+str(16*1)+" underline"),
    anchor="nw"
)
su_button.place(x=142, y=625)


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    235.0,
    215.0,
    image=image_image_1
)


# ID & PW Underline
canvas.create_rectangle(
    145.0,
    492.9999809265137,
    352.0,
    493.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    145.0,
    577.9999847412109,
    352.0,
    578.0,
    fill="#000000",
    outline="")


window.resizable(False, False)
window.mainloop()
