
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import tkinter
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.iconbitmap(relative_to_assets("3_icon.ico"))
window.title("UDA Chat")
window.geometry("450x700")
window.configure(bg = "#FFF5EB")

login_id = ''
login_pw = ''


canvas = Canvas(
    window,
    bg = "#FFF5EB",
    height = 700,
    width = 450,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    90.8773193359375,
    466.91,
    anchor="nw",
    text="ID",
    fill="#000000",
    font=("Arial", 17 * -1)
)

canvas.create_text(
    34.14,
    553.13,
    anchor="nw",
    text="PW",
    fill="#000000",
    font=("Arial", 17 * -1)
)


# If login_Button State == 'Active'
def sign_in():
    ID = entry_id.get()
    PW = entry_pw.get()

    tkinter.messagebox.showerror("ID", ID)
    tkinter.messagebox.showerror("PW", PW)

# If su_button state == 'Active'
def sign_up():
    pass


# ID & PW Entry
entry_id = Entry(window, font=('Arial 12'), bd = 0, textvariable = login_id)
entry_pw = Entry(window, font=('Arial 12'), bd = 0, show ='*', textvariable = login_pw)
entry_id.place(x = 132, y = 493, width = 207, height = 30)
entry_pw.place(x = 132, y = 578, width = 207, height = 30)


# Sign In Button
si_button = tkinter.Button(
    window,
    command=sign_in,
    bd=0,
    bg='#FFF5EB',
    activebackground='#FFF5EB',
    text='Sign In',
    font=("Arial " + str(16 * 1) + " underline"),
    anchor="nw"
)
si_button.place(x=263, y=625)

# Sign Up Button
su_button = tkinter.Button(
    window,
    command= sign_up,
    bd=0,
    bg='#FFF5EB',
    activebackground='#FFF5EB',
    text='Sign Up',
    font=("Arial "+str(16*1)+" underline"),
    anchor="nw"
)
su_button.place(x=142, y=625)


# Login Frame logo
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    279.0,
    279.0,
    image=image_image_1
)


# ID & PW Underline
canvas.create_rectangle(
    103.0,
    494.99998474121094,
    310.0,
    495.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    103.0,
    579.9999694824219,
    310.0,
    580.0,
    fill="#000000",
    outline="")


id_server = []
pw_server = []
# If the server doesn't have an ID
def login_notice():
    pass


window.resizable(False, False)
window.mainloop()